# Generated by Django 5.1.4 on 2025-05-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('ceo', 'CEO'), ('chro', 'CHRO'), ('cfo', 'CFO'), ('cso', 'CSO'), ('cdo', 'CDO'), ('cmo', 'CMO')], max_length=20),
        ),
    ]
