- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service (Linux)'
  inputs:
    azureSubscription: 'azure-savi-connection'  # This must be an existing, valid service connection
    appType: 'webAppLinux'
    appName: 'SAVI-AI'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
    runtimeStack: 'PYTHON|3.10'
    deploymentMethod: 'auto'
    startupCommand: 'gunicorn savi_ai.wsgi:application --bind=0.0.0.0 --timeout 600'
    resourceGroupName: 'your-resource-group-name'
    deployToSlotOrASE: true
    slotName: 'production'
