- task: AzureRmWebAppDeployment@5
  displayName: 'Deploy Django Backend to Azure App Service'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'SAVIAITDTLServiceConnection'
    appType: 'webAppLinux'
    WebAppName: 'SAVI-AI'
    resourceGroupName: 'your-resource-group-name'  # Replace with actual RG name
    packageForLinux: '$(Build.ArtifactStagingDirectory)/app.zip'
    RuntimeStack: 'PYTHON|3.12'
    StartupCommand: 'gunicorn savi_ai.wsgi:application --bind=0.0.0.0 --timeout 600'
    DeploymentTypeLinux: 'oneDeploy'
    deployToSlotOrASE: true
    slotName: 'production'
