# Generated by Django 5.1.4 on 2025-05-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('customer_id', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_segment', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('warehouse_id', models.CharField(max_length=50)),
                ('sales_rep_id', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('lead_time', models.IntegerField(help_text='Days to deliver')),
                ('reorder_quantity', models.IntegerField()),
                ('inventory_before', models.IntegerField()),
                ('inventory_after', models.IntegerField()),
                ('days_to_expiry', models.IntegerField()),
            ],
        ),
    ]
